### ISSUE TITLE
Webassembly API example

### ISSUE THREAD

**Issue by michail-vestnik** [grain-lang/grain-web-example#3]
Hi! 

How run wasm (Grain) code in browser WITHOUT grain-runner-browser.js?
Example:

```js
WebAssembly.instantiateStreaming(fetch('myModule.wasm'), importObject)
.then(obj => {
    // Call an exported function:
    obj.instance.exports.exportedFunc();
})
```
The grain-runner-browser.js file will kill all the usefulness of the wasm file and significantly ruin the performance effect (37,000 lines of JS code to load, interpret, etc.).

Wasm from Golang and Rust also supply "js-bridges", but they are less than 10 kb!

**Comment by ospencer** [comment]
You can run Grain programs just like any other wasm modules in the browser (just like your example). However, Grain currently only targets WASI, so you need to provide a WASI polyfill to get it to work in the browser. The Grain runner will do this for you but you could instead use something like https://github.com/wasmerio/wasmer-js to get it working.

**Comment by michail-vestnik** [comment]
Thank you!
I'll give it a try.
Good luck with your very promising project!
